baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: bap-nielsmoens_EN
primary: true
siteGroup: 52cb5f57-6c9b-4be6-9f84-62c3ad0bb57a # bap-nielsmoens
sortOrder: 1
