currLabel: 'Plugin Store'
customIcon: ''
enabled: 1
handle: plugin-store
icon: plugin
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: 0
order: 11
prevLabel: 'Plugin Store'
prevUrl: plugin-store
type: ''
url: plugin-store
