currLabel: Assets
customIcon: ''
enabled: 1
handle: assets
icon: assets
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: 0
order: 5
prevLabel: Assets
prevUrl: assets
type: ''
url: assets
