currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: assets
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: false
order: 4
prevLabel: Assets
prevUrl: assets
type: ''
url: assets
