currLabel: Categories
customIcon: ''
enabled: 1
handle: categories
icon: categories
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: 0
order: 4
prevLabel: Categories
prevUrl: categories
type: ''
url: categories
