currLabel: Categories
customIcon: null
enabled: true
handle: categories
icon: categories
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: false
order: 3
prevLabel: Categories
prevUrl: categories
type: ''
url: categories
