currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: section
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: false
order: 1
prevLabel: Entries
prevUrl: entries
type: ''
url: entries
