currLabel: Forms
customIcon: ''
enabled: 1
handle: freeform
icon: ''
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: 0
order: 7
prevLabel: Freeform
prevUrl: freeform
type: ''
url: freeform
