currLabel: Globals
customIcon: ''
enabled: 1
handle: globals
icon: globe
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: 0
order: 3
prevLabel: Globals
prevUrl: globals
type: ''
url: globals
