currLabel: Globals
customIcon: null
enabled: true
handle: globals
icon: globe
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: false
order: 2
prevLabel: Globals
prevUrl: globals
type: ''
url: globals
