currLabel: Settings
customIcon: ''
enabled: '1'
handle: settings
icon: settings
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: '0'
order: 10
prevLabel: Settings
prevUrl: settings
type: ''
url: settings
