currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: settings
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: false
order: 8
prevLabel: Settings
prevUrl: settings
type: ''
url: settings
