currLabel: Users
customIcon: null
enabled: true
handle: users
icon: users
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: false
order: 9999
prevLabel: Users
prevUrl: users
type: ''
url: users
