currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: tool
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: false
order: 7
prevLabel: Utilities
prevUrl: utilities
type: ''
url: utilities
