currLabel: Utilities
customIcon: ''
enabled: '1'
handle: utilities
icon: tool
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: '0'
order: '8'
prevLabel: Utilities
prevUrl: utilities
type: ''
url: utilities
