defaultPlacement: end
enableVersioning: true
handle: ender5
name: Ender-5
propagationMethod: all
siteSettings:
  f4a3df03-9dd3-4b04-8fb7-c6d007843eb4: # fablab-webapp
    enabledByDefault: true
    hasUrls: true
    template: machines\3dprinters\Ender-5.twig
    uriFormat: ender-5
type: single
