defaultPlacement: end
enableVersioning: true
handle: locations
name: locations
propagationMethod: all
siteSettings:
  f4a3df03-9dd3-4b04-8fb7-c6d007843eb4: # fablab-webapp
    enabledByDefault: true
    hasUrls: true
    template: locations/_entry
    uriFormat: 'locations/{slug}'
structure:
  maxLevels: null
  uid: 6f022af4-6090-4b9c-bc7b-6356b229f619
type: structure
