defaultPlacement: end
enableVersioning: true
handle: reportProblem
name: ReportProblem
propagationMethod: all
siteSettings:
  f4a3df03-9dd3-4b04-8fb7-c6d007843eb4: # fablab-webapp
    enabledByDefault: true
    hasUrls: true
    template: ReportProblem\reportProblem.twig
    uriFormat: reportproblem
type: single
