defaultPlacement: end
enableVersioning: true
handle: safetyOverview
name: 'Safety Overview'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f4a3df03-9dd3-4b04-8fb7-c6d007843eb4: # fablab-webapp
    enabledByDefault: true
    hasUrls: true
    template: safety/index.twig
    uriFormat: safety
type: single
