columnSuffix: null
contentColumnType: string
fieldGroup: 66f566b6-261d-4293-820c-28d42ea78c31 # detail machine elements
handle: categorytitle
instructions: ''
name: categoryTitle
searchable: false
settings:
  contentTable: '{{%matrixcontent_categorytitle}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
