columnSuffix: dncjzafn
contentColumnType: text
fieldGroup: 5c64d819-0d02-4285-a033-940cd7b8e347 # Home
handle: homeInfo
instructions: ''
name: 'Home Info'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '20'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
