columnSuffix: null
contentColumnType: string
fieldGroup: 5c64d819-0d02-4285-a033-940cd7b8e347 # Home
handle: infoGrid
instructions: ''
name: 'Info Grid '
searchable: false
settings:
  contentTable: '{{%matrixcontent_infogrid}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
