columnSuffix: null
contentColumnType: string
fieldGroup: 66f566b6-261d-4293-820c-28d42ea78c31 # machines
handle: instructions
instructions: ''
name: Instructions
searchable: false
settings:
  contentTable: '{{%matrixcontent_instructions}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
