columnSuffix: null
contentColumnType: string
fieldGroup: 5c64d819-0d02-4285-a033-940cd7b8e347 # Home
handle: locations
instructions: ''
name: Locations
searchable: false
settings:
  allowSelfRelations: false
  limit: '8'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:19621fb7-4303-43d5-82d3-f19d17cd5a89'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
