columnSuffix: xlwlxvsj
contentColumnType: text
fieldGroup: 5a0fc7d3-92eb-468e-94c0-cc7f51754247 # Navigation
handle: navigation
instructions: "Edit, add or delete the main navigation menu for the website\r\nIf you want a different Icon then the default icon label, visit https://materialdesignicons.com/ to get the correct icon label"
name: Navigation
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Navigation Label'
            -
              - handle
              - navigationLabel
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Navigation URL'
            -
              - handle
              - navigationUrl
            -
              - width
              - ''
            -
              - type
              - url
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Icon Label'
            -
              - handle
              - iconlabel
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - 'Report A Problem'
        -
          - col2
          - /reportproblem
        -
          - col3
          - ''
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Table
