columnSuffix: klxdvyqo
contentColumnType: text
fieldGroup: 3d4c2feb-eaf0-41db-91e4-07c768e2d2d8 # Safety
handle: safetyDescription
instructions: 'Describe the important safety rules for this kind of equipment '
name: 'Safety description'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: ''
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
