currLabel: Entries
customIcon: ''
enabled: '1'
handle: entries
icon: section
layout: 644bc34f-dfa9-4202-8f72-b7098b959238 # Default
newWindow: '0'
order: 2
prevLabel: Entries
prevUrl: entries
type: ''
url: entries
