fieldLayouts:
  ab447c40-28ab-4d56-8c01-25a3238769c7:
    tabs:
      -
        elements:
          -
            fieldUid: 6d8ae871-ae05-4015-befa-2067e9ed8910 # locationImage
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 1a9b64ed-f87b-4ec2-ae7b-9b7498caf125 # Location Important Announcement 
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4d52fefb-b6e3-4adf-8bac-489be8cf5003 # Openinghours Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 493bc15e-78ef-4169-a8e1-7c60b35441bc # opening hours
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a08bfe21-0581-468f-a45b-2271e49f7f31 # Location Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a3d83619-8019-4c63-8902-c7a368e044be # Location Address
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 26311269-ed71-49df-898d-e9dc3f47d8bc # Location Section Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 240ee863-c956-4719-a271-ebb13bef6c1b # Location Contact Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e88c79a3-b1c8-43e8-bb2c-10a990089786 # Location Contact Phone number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 787d1e12-e83b-4d3b-94d3-338c4812d321 # Location Extra Contact
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 69748453-5990-4173-bb2d-589424d6765d # Machines On Locations Title 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 778103a3-d3ce-4b8c-8ee3-6a120d9af162 # Machines On Location
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: default
hasTitleField: true
name: Locations
section: dcaea295-d65f-4a92-a262-d60c36f61870 # locations
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
