field: cf588925-1a01-4ebd-aed0-25bcda088df5 # categoryTitle
fieldLayouts:
  dd7c68f4-8011-48b5-aab6-d832ebc3bbc8:
    tabs:
      -
        elements:
          -
            fieldUid: 08c4ffa1-7de8-4d78-a5d8-17e0c937228d # categoryName
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  08c4ffa1-7de8-4d78-a5d8-17e0c937228d: # categoryName
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: categoryName
    instructions: ''
    name: categoryName
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: categoryTitle
name: categoryTitle
sortOrder: 1
