columnSuffix: ygjvlzxm
contentColumnType: string
fieldGroup: 6b8a5f7b-0fdc-4b5c-9030-63dc5e42e90d # locations
handle: locationContactEmail
instructions: 'fill in u preferred email address to contact you '
name: 'Location Contact Email'
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
