columnSuffix: oxmzfjal
contentColumnType: string(80)
fieldGroup: 6b8a5f7b-0fdc-4b5c-9030-63dc5e42e90d # locations
handle: locationContactPhoneNumber
instructions: 'Fill in the contact phone number'
name: 'Location Contact Phone number'
searchable: false
settings:
  byteLimit: null
  charLimit: 20
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
