columnSuffix: tnxdfnlm
contentColumnType: text
fieldGroup: 6b8a5f7b-0fdc-4b5c-9030-63dc5e42e90d # locations
handle: openingHours
instructions: ''
name: 'opening hours'
searchable: false
settings:
  slots:
    __assoc__:
      -
        - open
        -
          __assoc__:
            -
              - name
              - 'Opening Time'
            -
              - handle
              - open
      -
        - close
        -
          __assoc__:
            -
              - name
              - 'Closing Time'
            -
              - handle
              - close
      -
        - slot1
        -
          __assoc__:
            -
              - name
              - 'Second Open'
            -
              - handle
              - secondOpen
      -
        - slot2
        -
          __assoc__:
            -
              - name
              - 'Second Close'
            -
              - handle
              - secondClose
translationKeyFormat: null
translationMethod: none
type: craft\storehours\Field
