columnSuffix: frkeiunh
contentColumnType: string(1020)
fieldGroup: 66f566b6-261d-4293-820c-28d42ea78c31 # machines
handle: reportAProblemTitle
instructions: ''
name: 'Report A Problem Title '
searchable: false
settings:
  byteLimit: null
  charLimit: 255
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
