columnSuffix: psgwgzex
contentColumnType: text
fieldGroup: 66f566b6-261d-4293-820c-28d42ea78c31 # machines
handle: safetyBannerContent
instructions: ''
name: 'Safety Banner Content'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '3'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
