dateModified: 1658788660
email:
  fromEmail: niels.moens@student.arteveldehs.be
  fromName: fablab-webapp
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/sbin/sendmail -bs'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0a6b2392-15f9-4871-85b2-3c0338acf55c: Default # Default
    0db80961-0ad7-479f-8fd6-b9729841bcd2: Login # Login
    1a9b64ed-f87b-4ec2-ae7b-9b7498caf125: 'Location Important Announcement ' # Location Important Announcement 
    2e7bf592-27b5-4b06-a3d5-e232876f3252: 'Main Navigation' # Main Navigation
    2f16e750-2bae-4f59-aa71-f3feb4988313: 'Report Problem' # Report Problem
    3d4c2feb-eaf0-41db-91e4-07c768e2d2d8: Safety # Safety
    4d52fefb-b6e3-4adf-8bac-489be8cf5003: 'Openinghours Title' # Openinghours Title
    5a0fc7d3-92eb-468e-94c0-cc7f51754247: Navigation # Navigation
    5c64d819-0d02-4285-a033-940cd7b8e347: Home # Home
    5c90a701-e0e4-4d9d-8f25-997db8296b92: Register # Register
    6b8a5f7b-0fdc-4b5c-9030-63dc5e42e90d: locations # locations
    6c0b2789-5e52-41de-84a2-8719c0ad32d7: 'Home Info' # Home Info
    6c70c20a-4aee-4f21-b4ff-52ebaf36a707: Description # Description
    6d8ae871-ae05-4015-befa-2067e9ed8910: locationImage # locationImage
    6db30543-78ca-4e93-917f-45086706d3fa: Homepage # Homepage
    6ef1d014-6a1a-4801-a997-80bd5686a24d: 'Card Title ' # Card Title 
    6f3dd8cb-0971-44e6-8ccf-2b2cdf725dcb: 'Safety Overview' # Safety Overview
    7add9c0f-f1dd-4e3d-a45a-4ad6885643a8: machine # machine
    7c9f2036-f424-4156-b700-4c50700e96b7: 'locations Title' # locations Title
    8a9ecc9c-b8f7-422f-8ae9-c84aded30df4: 'Login Image' # Login Image
    8a11ff46-6934-4c8a-ba67-76eee055fbfc: Locations # Locations
    8a8363b0-64f6-49ae-a25a-0d7066de4306: IconLabel # IconLabel
    8aaf66bb-effb-454a-84cd-de2f67abc9ca: 'Safety Signs' # Safety Signs
    8adfccea-c28b-443e-b085-a479432c7469: SafetyType # SafetyType
    08c4ffa1-7de8-4d78-a5d8-17e0c937228d: categoryName # categoryName
    9ff9100d-6e98-48f4-9380-ab73833cbfec: 'locations Overview' # locations Overview
    21fd470b-2e2a-4d94-99b9-60ca8ed158fa: 'Machines Overview' # Machines Overview
    0033a93a-5f40-4e37-a832-6e2ff1d68222: 'Info Grid ' # Info Grid 
    52cb5f57-6c9b-4be6-9f84-62c3ad0bb57a: bap-nielsmoens # bap-nielsmoens
    66f566b6-261d-4293-820c-28d42ea78c31: machines # machines
    71ee94e7-a545-4cae-8239-98119028b390: Instructions # Instructions
    80e4aa5d-eb4f-4829-969a-db66c4f40560: Homepage # Homepage
    84cca4ae-aa2e-4759-a1f1-c1946eed4767: 'locations Overview Description' # locations Overview Description
    87a7f903-c6b6-4783-80ab-b3ce75ae899e: 'Machines Overview' # Machines Overview
    89d69fb1-217d-43b2-bf94-aa84ea1d19e9: 'Machine Type' # Machine Type
    240ee863-c956-4719-a271-ebb13bef6c1b: 'Location Contact Email' # Location Contact Email
    265daf01-d602-4dd9-8b79-bc81316b237d: 'Report Problem' # Report Problem
    271ed0fe-b6ba-432c-858e-7be5dba20f18: 'Welcome Title' # Welcome Title
    0433a068-a333-46ec-ba43-870dfbb5a5c6: Uploads # Uploads
    440ca2f6-c43c-4a7c-b436-1366abbc1b24: 'Machine Image ' # Machine Image 
    464c1466-ccad-45b1-acd2-356c76ddd81b: 'footer text' # footer text
    473f1563-91b2-48a8-ad8a-c2c2e704553f: 'Navigation Category Item' # Navigation Category Item
    493bc15e-78ef-4169-a8e1-7c60b35441bc: 'opening hours' # opening hours
    512cad3f-3105-4a81-b185-3839be63ac50: 'Locations Overview Title ' # Locations Overview Title 
    644bc34f-dfa9-4202-8f72-b7098b959238: Default # Default
    00738fd8-71aa-43a1-a75e-4a54311e2180: bap-nielsmoens_NL # bap-nielsmoens_NL
    787d1e12-e83b-4d3b-94d3-338c4812d321: 'Location Extra Contact' # Location Extra Contact
    0845fdb0-dae4-4de9-ace1-aa4bec536fa2: 'Safety Banner Content' # Safety Banner Content
    1118ac18-cbfe-4485-88d6-2c959b1ce05c: 'Instruction Title' # Instruction Title
    3210a91b-7577-4b33-b82c-d0c44ba2401a: Safety # Safety
    7532d59e-774f-407b-97dc-a0726c477e05: 'Safety description' # Safety description
    9639da72-9f64-4038-8ff5-2e80c35743aa: 'Info Grid' # Info Grid
    13686ec0-4285-48f1-8c05-ee82779c4e47: 'OpeningHours Closed Message' # OpeningHours Closed Message
    14503d33-2594-47c7-9f55-82e3e31f5779: Register # Register
    63968b99-7ac3-452d-9f8e-868915d51c25: 'Section title' # Section title
    73941db8-6433-4a59-a3bc-60a9007faed7: MainNavigation # MainNavigation
    282615d1-bebd-4758-b626-4923f52eaca7: Navigation # Navigation
    0294142d-277b-49ae-827c-06fa9fa3ce09: 'Machines Overview Description' # Machines Overview Description
    778103a3-d3ce-4b8c-8ee3-6a120d9af162: 'Machines On Location' # Machines On Location
    950940db-3479-4e9b-807b-edb6561ed0f9: Locations # Locations
    5873007c-c78f-45fb-bb69-53c0cfa1cd46: Instructions # Instructions
    26311269-ed71-49df-898d-e9dc3f47d8bc: 'Location Section Title' # Location Section Title
    58426747-4527-4e01-83eb-8fffa431392c: 'Report Problem Image' # Report Problem Image
    69748453-5990-4173-bb2d-589424d6765d: 'Machines On Locations Title ' # Machines On Locations Title 
    a0614031-9535-47ed-adc3-fd7a00af5e90: 'locations Overview' # locations Overview
    a08bfe21-0581-468f-a45b-2271e49f7f31: 'Location Description' # Location Description
    a3d83619-8019-4c63-8902-c7a368e044be: 'Location Address' # Location Address
    a4e4a601-301b-4fdb-ae5b-c6adc4bc98e7: 'Card link' # Card link
    a9aa0fe6-f7d7-4ae8-81c3-ce7074ed7c58: 'Instructions Section Title' # Instructions Section Title
    adb07908-345b-4249-8af1-51c931c76be4: 'Safety Overview' # Safety Overview
    adb4857c-6edd-4edd-99d6-bbace9cee9b3: 'OpeningsHours Come Back Tomorrow message ' # OpeningsHours Come Back Tomorrow message 
    af0bfecc-78dd-4e4f-9584-29bbfdd8a269: machines # machines
    b0f1416e-fefb-45fe-a245-41ddc2404efe: Login # Login
    b4ac6aaa-6972-4bda-bd52-af5446ad1ed9: 'OpeningsHours Open Message' # OpeningsHours Open Message
    b9b9577a-0df2-4f57-bdd4-90cf609c5cff: sub # sub
    b71257cc-2010-4297-9163-f1f60dd5ac31: General # General
    be05fcff-4c8b-447e-a0f6-726827d24625: 'Locations description' # Locations description
    c04050cf-d6e9-45b3-b695-31589119f32e: Navigation # Navigation
    c247021a-bb7b-4237-b3bc-b24e695267b7: 'Card Thumbnail' # Card Thumbnail
    ca728082-3604-498c-9fad-83653bb83d5f: Descprition # Descprition
    d0d78113-f6d1-4750-af4e-cdd603d4a59a: 'Button Link text ' # Button Link text 
    d2df09db-06bd-4a28-bc88-68538250a29f: Login # Login
    d190d192-a79f-4e61-afbb-4ff8a197cee3: 'Locations Thumbnail' # Locations Thumbnail
    d839a26f-cbee-468b-95c9-7fe5f10732e0: 'Login Description' # Login Description
    d2697d86-879b-4266-b90c-17d82fc36eda: 'Machines Overview Title' # Machines Overview Title
    da445cf6-97b8-410a-9098-fb4ef5859baf: 'Report Problem Info' # Report Problem Info
    db37d21f-e9bc-46f3-89dc-1bb2bb236dc3: machines # machines
    dcaea295-d65f-4a92-a262-d60c36f61870: locations # locations
    df4a5294-7ee3-46e6-bf5a-15fc841cff17: 'Navigation Category' # Navigation Category
    e9a4a87f-69e8-4116-9e55-7d7c6c005241: footer # footer
    e88c79a3-b1c8-43e8-bb2c-10a990089786: 'Location Contact Phone number' # Location Contact Phone number
    f2aca6ca-2bf9-4696-a513-85e119aeaf3d: 'Report Problem Title ' # Report Problem Title 
    f4a3df03-9dd3-4b04-8fb7-c6d007843eb4: bap-nielsmoens_EN # bap-nielsmoens_EN
    f5ae64bc-6530-4565-966c-d29594de6f43: 'Report A Problem Title ' # Report A Problem Title 
    fb749a8b-744b-4404-ae8c-fb5b8ee233c4: Default # Default
    ff8021a4-7fe4-4b11-b1f2-3f86bee08b16: 'Nozzle ' # Nozzle 
plugins:
  cp-nav:
    edition: standard
    enabled: true
    schemaVersion: 2.0.7
    settings:
      originalNavHash:
        __assoc__:
          -
            - 00830468-14f7-45ad-a4c6-19630f36c23a
            - W3sibGFiZWwiOiJEYXNoYm9hcmQiLCJ1cmwiOiJkYXNoYm9hcmQiLCJmb250SWNvbiI6ImdhdWdlIn0seyJsYWJlbCI6IkVudHJpZXMiLCJ1cmwiOiJlbnRyaWVzIiwiZm9udEljb24iOiJzZWN0aW9uIn0seyJsYWJlbCI6Ikdsb2JhbHMiLCJ1cmwiOiJnbG9iYWxzIiwiZm9udEljb24iOiJnbG9iZSJ9LHsibGFiZWwiOiJDYXRlZ29yaWVzIiwidXJsIjoiY2F0ZWdvcmllcyIsImZvbnRJY29uIjoiY2F0ZWdvcmllcyJ9LHsibGFiZWwiOiJBc3NldHMiLCJ1cmwiOiJhc3NldHMiLCJmb250SWNvbiI6ImFzc2V0cyJ9LHsibGFiZWwiOiJVc2VycyIsInVybCI6InVzZXJzIiwiZm9udEljb24iOiJ1c2VycyJ9LHsibGFiZWwiOiJGaWVsZCBNYW5hZ2VyIiwidXJsIjoiZmllbGQtbWFuYWdlciIsImljb24iOiIvaG9tZS9jeWJlci9wcm9qZWN0cy9OaWVsc01vZW5zLTNOTUQtQkFQLTIwMjEtMjAyMi9mYWJsYWItd2ViYXBwL3ZlbmRvci92ZXJiYi9maWVsZC1tYW5hZ2VyL3NyYy9pY29uLW1hc2suc3ZnIn0seyJsYWJlbCI6IkZyZWVmb3JtIiwidXJsIjoiZnJlZWZvcm0iLCJpY29uIjoiL2hvbWUvY3liZXIvcHJvamVjdHMvTmllbHNNb2Vucy0zTk1ELUJBUC0yMDIxLTIwMjIvZmFibGFiLXdlYmFwcC92ZW5kb3Ivc29sc3BhY2UvY3JhZnQtZnJlZWZvcm0vcGFja2FnZXMvcGx1Z2luL3NyYy9pY29uLW1hc2suc3ZnIiwic3VibmF2Ijp7ImRhc2hib2FyZCI6eyJsYWJlbCI6IkRhc2hib2FyZCIsInVybCI6ImZyZWVmb3JtL2Rhc2hib2FyZCJ9LCJzdWJtaXNzaW9ucyI6eyJsYWJlbCI6IlN1Ym1pc3Npb25zIiwidXJsIjoiZnJlZWZvcm0vc3VibWlzc2lvbnMifSwic3BhbSI6eyJsYWJlbCI6IlNwYW0iLCJ1cmwiOiJmcmVlZm9ybS9zcGFtIn0sImZvcm1zIjp7ImxhYmVsIjoiRm9ybXMiLCJ1cmwiOiJmcmVlZm9ybS9mb3JtcyJ9LCJmaWVsZHMiOnsibGFiZWwiOiJGaWVsZHMiLCJ1cmwiOiJmcmVlZm9ybS9maWVsZHMifSwibm90aWZpY2F0aW9ucyI6eyJsYWJlbCI6IkVtYWlsIE5vdGlmaWNhdGlvbnMiLCJ1cmwiOiJmcmVlZm9ybS9ub3RpZmljYXRpb25zIn0sInNldHRpbmdzIjp7ImxhYmVsIjoiU2V0dGluZ3MiLCJ1cmwiOiJmcmVlZm9ybS9zZXR0aW5ncyJ9LCJyZXNvdXJjZXMiOnsibGFiZWwiOiJSZXNvdXJjZXMiLCJ1cmwiOiJmcmVlZm9ybS9yZXNvdXJjZXMifX19LHsibGFiZWwiOiJHcmFwaFFMIiwidXJsIjoiZ3JhcGhxbCIsImljb24iOiJAYXBwaWNvbnMvZ3JhcGhxbC5zdmciLCJzdWJuYXYiOnsic2NoZW1hcyI6eyJsYWJlbCI6IlNjaGVtYXMiLCJ1cmwiOiJncmFwaHFsL3NjaGVtYXMifSwidG9rZW5zIjp7ImxhYmVsIjoiVG9rZW5zIiwidXJsIjoiZ3JhcGhxbC90b2tlbnMifSwiZ3JhcGhpcWwiOnsibGFiZWwiOiJHcmFwaGlRTCIsInVybCI6ImdyYXBoaXFsIiwiZXh0ZXJuYWwiOnRydWV9fX0seyJ1cmwiOiJ1dGlsaXRpZXMiLCJsYWJlbCI6IlV0aWxpdGllcyIsImZvbnRJY29uIjoidG9vbCIsImJhZGdlQ291bnQiOjkxfSx7InVybCI6InNldHRpbmdzIiwibGFiZWwiOiJTZXR0aW5ncyIsImZvbnRJY29uIjoic2V0dGluZ3MifSx7InVybCI6InBsdWdpbi1zdG9yZSIsImxhYmVsIjoiUGx1Z2luIFN0b3JlIiwiZm9udEljb24iOiJwbHVnaW4ifV0=
  dumper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: lite
    enabled: true
    licenseKey: 3Y2K6T6AMK1N9BH1M94Y84FK
    schemaVersion: 3.5.1
    settings:
      ajaxByDefault: true
      alertNotificationRecipients: null
      autoScroll: true
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      clientDigestFrequency: 1
      clientDigestRecipients: null
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: dashboard
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: null
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formFieldShowOnlyAllowedForms: false
      formSubmitDisable: true
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: flexbox.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: true
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: null
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaLazyLoad: false
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      rememberPageSubmitOrder: true
      removeNewlines: false
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      saveFormSessionLimit: 10
      saveFormTtl: 30
      scriptInsertLocation: footer
      scriptInsertType: pointers
      sessionContext: payload
      sessionContextCount: 100
      sessionContextSecret: ''
      sessionContextTimeToLiveMinutes: 180
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: false
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: true
  manytomany:
    edition: standard
    enabled: false
    schemaVersion: 1.0.2
  reasons:
    edition: standard
    enabled: false
    schemaVersion: 2.1.1
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  store-hours:
    edition: standard
    enabled: true
    schemaVersion: 1.0.2
  super-table:
    edition: standard
    enabled: false
    schemaVersion: 2.2.1
  support:
    edition: standard
    enabled: true
    schemaVersion: 0.1.0
system:
  edition: pro
  live: true
  name: $DB_USER
  retryDuration: null
  schemaVersion: 3.7.33
  timeZone: Europe/Brussels
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
