defaultPlacement: end
enableVersioning: true
handle: register
name: Register
propagationMethod: all
siteSettings:
  00738fd8-71aa-43a1-a75e-4a54311e2180: # bap-nielsmoens_NL
    enabledByDefault: true
    hasUrls: true
    template: register/_entry
    uriFormat: register
  f4a3df03-9dd3-4b04-8fb7-c6d007843eb4: # bap-nielsmoens_EN
    enabledByDefault: true
    hasUrls: true
    template: register/_entry
    uriFormat: register
type: single
