fieldLayouts:
  0dcbcc54-4e2e-462c-a026-b611e7f1ea4f:
    tabs:
      -
        elements:
          -
            fieldUid: 2e7bf592-27b5-4b06-a3d5-e232876f3252 # Main Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 282615d1-bebd-4758-b626-4923f52eaca7 # Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Navigation '
        sortOrder: 1
handle: navigation
name: Navigation
sortOrder: 2
