fieldLayouts:
  d26a43e2-0927-4257-a901-a2ce5a48f7e8:
    tabs:
      -
        elements:
          -
            fieldUid: 464c1466-ccad-45b1-acd2-356c76ddd81b # footer text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: footer
        sortOrder: 1
handle: footer
name: footer
sortOrder: 3
