fieldLayouts:
  1d8fdefc-e401-46b9-a527-4bcff7d8fd22:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 440ca2f6-c43c-4a7c-b436-1366abbc1b24 # machine Image 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6c70c20a-4aee-4f21-b4ff-52ebaf36a707 # detail Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'detail Page Content'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: cf588925-1a01-4ebd-aed0-25bcda088df5 # categoryTitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: categories
        sortOrder: 2
handle: default
hasTitleField: true
name: Default
section: af0bfecc-78dd-4e4f-9584-29bbfdd8a269 # machines
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
