fieldLayouts:
  e93720b0-c845-414f-84ea-22e508b2d447:
    tabs:
      -
        elements:
          -
            fieldUid: 6c70c20a-4aee-4f21-b4ff-52ebaf36a707 # detail Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cf588925-1a01-4ebd-aed0-25bcda088df5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: __blank__
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: 'Subject category'
        sortOrder: 1
handle: subjectCategory
hasTitleField: false
name: 'subject category'
section: 90e49b5f-07b8-4145-826b-3852c9aebb1f # machines list
sortOrder: 2
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
